name: Update pnpm-lock.yaml

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-lockfile:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies without frozen lockfile
        run: pnpm install --no-frozen-lockfile

      - name: Commit updated pnpm-lock.yaml
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add pnpm-lock.yaml
          git commit -m 'Update pnpm-lock.yaml'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
